robototes/Reefscape2025

src/main/java/frc/robot/Hardware.java

elevator motor IDs created. currently occupying spaces 21 and 22

elevator motor IDs

---

src/main/java/frc/robot/Hardware.java

Just added the one comment
// Swerve: 1-12

Singular comment for swerve ID's

---

src/main/java/frc/robot/Controls.java

Assigned controls, taken from the beta bot, but only for the drivebase. removed some unnecessary fluff.

Making it drive

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Subsystems.java
src/main/java/frc/robot/subsystems/ArmPivot.java

added motor to arm pivot class as well.

added ArmPivot

---

build.gradle
src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Subsystems.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java

added test elevator code. should zero out any current values before testing

Elevator Subsystem 1-18 creation

---

build.gradle
vendordeps/Phoenix6-25.2.1.json
vendordeps/libgrapplefrc2025.json

also updated wpilib and phoenix

Grapple vendor dep added

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Hardware.java
src/main/java/frc/robot/Subsystems.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

Made the subsystem file, made constants in hardware

Started Climb Subsystem

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Subsystems.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java

created and works with an error of about .04

Elevator Reset Zero Position Command

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/subsystems/ArmPivot.java
src/main/java/frc/robot/subsystems/ClimbPivot.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java

also reorganized controls binding order to match the order they are bound

Code Cleanup

---

src/main/java/frc/robot/Hardware.java

Update Hardware.java (NFC)

---

src/main/java/frc/robot/subsystems/ArmPivot.java
src/main/java/frc/robot/subsystems/ClimbPivot.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
src/main/java/frc/robot/subsystems/SpinnyClaw.java

Added alerts to check if motors are connected and display which motors aren't

Alert system

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Hardware.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

adds climb encoder functionality, holds funnel down.

Climb encoder

---

src/main/java/frc/robot/subsystems/VisionSubsystem.java
vendordeps/PathplannerLib-2025.2.6.json

we should to put this into main soon

Vision listener added and auto vendor deps update

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

Fixes #89 
Fixes #90 
Fixes #85

post WAAHS climb fixes/improvements

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Robot.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
src/main/java/frc/robot/subsystems/SuperStructure.java

code fix related to issue #84. untested as of 3/24.

Superstructure Post-WAAHS Fixes

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Hardware.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

various small climb fixes, made it work with new funnel hopefully maybe
fixes #104

Climb work 3/27

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

Various climb fixes 3/28

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/sensors/ArmSensor.java
src/main/java/frc/robot/subsystems/ArmPivot.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
src/main/java/frc/robot/subsystems/SpinnyClaw.java
src/main/java/frc/robot/subsystems/SuperStructure.java

commented out the ability to use ground intake from both driver and operator controllers until after coral ground intake mechanism has been tested with algae
position updates for superstructure stuff

Superstructure Changes 3/29

---

src/main/java/frc/robot/Controls.java

fixed LED null...  issue #119 :D!!!

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/subsystems/ArmPivot.java
src/main/java/frc/robot/subsystems/SpinnyClaw.java
src/main/java/frc/robot/subsystems/SuperStructure.java

Fixes #118, minus automatically going to pre-intake.

Pre dcmps superstructure fixes

---

src/main/java/frc/robot/subsystems/ElevatorSubsystem.java

Apparently leader motor hitting soft limit doesn't stop the follower

Remove elevator soft limits

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

cleaned up climb code, no longer two button triggers, 3 different button for each mode.

Climb cleaning

---

src/main/java/frc/robot/sensors/IntakeSensor.java
src/main/java/frc/robot/subsystems/ArmPivot.java
src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
src/main/java/frc/robot/subsystems/GroundArm.java
src/main/java/frc/robot/subsystems/GroundSpinny.java
src/main/java/frc/robot/subsystems/SuperStructure.java
src/main/java/frc/robot/subsystems/auto/AutoLogic.java
src/main/java/frc/robot/util/RobotType.java

Also fix typo in 3 piece path name, use the right competition MAC address, and make arm pivot faster.
Closes #131.

Ground intake improvements

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Robot.java
src/main/java/frc/robot/subsystems/ClimbPivot.java
src/main/java/frc/robot/subsystems/drivebase/CommandSwerveDrivetrain.java

I never want to do that again (I will though)

commenting Connor's subsystems

---

src/main/java/frc/robot/subsystems/ArmPivot.java

Increased current limits
Increased P
Increased Velocity and Jerk
Verified on real robot

Faster arm

---

src/main/deploy/pathplanner/autos/OSMRSF_E-D.auto
src/main/java/frc/robot/subsystems/SuperStructure.java
src/main/java/frc/robot/subsystems/auto/AutoLogic.java

#157 added a check to make sure coral can be in took and increased timeout for coral at station

Humanplayerautochanges

---

src/main/java/frc/robot/Controls.java
src/main/java/frc/robot/Hardware.java
src/main/java/frc/robot/subsystems/ClimbPivot.java

Automatically triggers the funnel to go to the CLIMBED state when its in CLIMB_OUT and detects the steel cage in teleop.

Auto climb
